version: '3'

services:

  dash_app:
    container_name: dash_app
    restart: always
    build: ./dash_app
    ports:
      - "8000:8000"
    environment:
      - TESLAMONITOR_WEBSERVICE_URL
      - TESLAMONITOR_WEBSERVICE_USER_ID
      - TESLAMONITOR_WEBSERVICE_PASSWORD
    command: gunicorn -w 1 -b :8000 app:server


  nginx:
    container_name: nginx
    restart: always
    build: ./nginx
    ports:
      - "8050:80"
    depends_on:
      - dash_app
